---
title: "7CBEm"
author: "pslacerda"
date: "`r Sys.Date()`"
output: html_document
---

# Inicialização
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(stringr)
library(viridis)
library(tidyr)
library(ggraph)
library(igraph)
library(topicmodels)
library(tidytext)
library(scales)
```

# Leitura e tratamento dos dados
```{r}
EIXOS = c(
  "Eixo 1 – Educação Escolar dos Povos Originários, Ancestrais e Tradicionais",
  "Eixo 2 – Etnomatemática na Educação Básica",
  "Eixo 3 – Etnomatemática na Educação Superior",
  "Eixo 4 – Etnomatemática e suas vertentes na Educação Matemática",
  "Eixo 5 – Etnomatemática e Relações Étnico-Raciais",
  "Eixo 6 – Práticas Pedagógicas e Pesquisas em Ciências e Matemática",
  "Eixo 7 – Conhecimentos Ancestrais em Ciências: Diálogos Interculturais"
)

MODALIDADES = c(
  "Comunicação oral",
  "Pôster"
)

F = read.csv("frequencias.csv") %>%
  mutate(
    Pdf = Pdf,
    Eixo = str_remove(Eixo, " Temático"),
    Eixo = str_remove(Eixo, "\\."),
    Eixo = str_replace(Eixo, "-", "–"),
    Eixo = Eixo,
    Modalidade = Modalidade,
    Termo = Termo
  )

T = read.csv("trabalhos.csv") %>%
  mutate(
    Pdf = Pdf,
    Eixo = str_remove(Eixo, " Temático"),
    Eixo = str_remove(Eixo, "\\."),
    Eixo = str_replace(Eixo, "-", "–"),
    Eixo = Eixo,
    Modalidade = Modalidade
  )

I = read.csv("instituicoes.csv") %>%
  transmute(
    Pdf = str_replace(ARTIGO, ".*/", ""),
    Pdf = Pdf,
    Autor = AUTOR,
    Instituição = INSTITUIÇÃO,
    Estado = UF
  )

Nordeste = c("AL", "BA", "CE", "MA", "PB", "PE", "PI", "RN", "SE")
```

# Produções por Estado, Instituição e Autor
```{r}
merge(I, T) %>%
  filter(
    !is.na(Estado)
  ) %>%
  group_by(Pdf) %>%
  mutate(
    Região = ifelse(Estado %in% Nordeste, "Nordeste", "Outra"),
    Eixo = str_replace(Eixo,".*(\\d).*", "\\1")
  ) %>%
  group_by(Região, Eixo) %>%
  tally() %>%
  ggplot(aes(y = Eixo, x = n, fill = Região)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single")) +
  labs(
    title = "Produção por Autor",
    subtitle = "Destaque à região Nordeste",
    x = "Autores"
  )

merge(I, T) %>%
  filter(
    Estado %in% Nordeste
  ) %>%
  select(Autor, Estado, Eixo, Modalidade) %>%
  distinct() %>%
  ggplot(aes(Estado, fill = Eixo)) +
  geom_bar(position = "stack") +
  scale_x_discrete(drop = FALSE) +
  scale_fill_viridis(discrete=TRUE, option="turbo") +
  facet_grid(. ~ Modalidade) +
  labs(
    y = "Total"
  ) +
  theme(
    legend.position="bottom",
    legend.direction = "vertical"
  )

I %>%
  filter(
    Estado %in% Nordeste
  ) %>%
  select(Autor, Instituição) %>%
  distinct() %>%
  ggplot(aes(Instituição)) +
  geom_bar()
```

# Frequência de termos

## Unigramas
```{r, fig.dim=c(8,8)}
merge(F, I, all = TRUE) %>%
  group_by(Pdf) %>%
  filter(
    any(Estado %in% Nordeste),
    Tipo == "Unigram"
  ) %>%
  group_by(Pdf, Termo) %>%
  filter(
    Autor == Autor[1]
  ) %>%
  select(-Autor) %>%
  count(Pdf, Eixo, Modalidade, Termo) %>%
  group_by(Pdf, Eixo, Modalidade) %>%
  mutate(
    Proporção = n / sum(n),
    Proporção = ifelse(is.na(Proporção), 0, Proporção)
  ) %>%
  ungroup() %>%
  complete(Pdf, Eixo, Modalidade, Termo, fill=list(Proporção=0), explicit=TRUE) %>%
  ungroup() %>%
  group_by(Eixo, Modalidade, Termo) %>%
  summarise(
    Proporção = mean(Proporção)
  ) %>%
  arrange(-Proporção) %>%
  filter(
    row_number() <= 10,
    Proporção > 0
  ) %>%
  group_by(Termo) %>%
  mutate(
    n = n()
  ) %>%
  ggplot(aes(y = Termo, x = Proporção, fill = Eixo)) +
  geom_bar(stat='identity', position = 'stack') +
  scale_fill_viridis(discrete=TRUE, option="turbo") +
  facet_wrap(Modalidade ~ ., scales = "free") +
  labs(
    title = "Corpus textual",
    subtitle = "Anais 7º CBEm",
    y = "Termos",
    X = "Proporção"
  ) +
  theme(
    legend.position="bottom",
    legend.direction = "vertical"
  )
```

## Bigramas
```{r, fig.dim=c(8,8)}
merge(F, I, all = TRUE) %>%
  group_by(Pdf) %>%
  filter(
    any(Estado %in% Nordeste),
    Tipo == "Bigram"
  ) %>%
  group_by(Pdf, Termo) %>%
  filter(
    Autor == Autor[1]
  ) %>%
  select(-Autor) %>%
  count(Pdf, Modalidade, Eixo, Termo) %>%
  group_by(Pdf) %>%
  mutate(
    Proporção = n / sum(n),
    Proporção = ifelse(is.na(Proporção), 0, Proporção)
  ) %>%
  ungroup() %>%
  complete(Pdf, Modalidade, Eixo, Termo, fill=list(Proporção=0), explicit=TRUE) %>%
  ungroup() %>%
  group_by(Modalidade, Eixo, Termo) %>%
  summarise(
    Proporção = mean(Proporção)
  ) %>%
  arrange(-Proporção) %>%
  filter(
    row_number() <= 10,
    Proporção > 0
  ) %>%
  group_by(Termo) %>%
  mutate(
    n = n()
  ) %>%
  ggplot(aes(y = Termo, x = Proporção, fill = Eixo)) +
  geom_bar(stat='identity', position = position_stack()) +
  scale_fill_viridis(discrete=TRUE, option="turbo") +
  facet_wrap(Modalidade ~ ., scales = "free") +
  labs(
    title = "Corpus textual",
    subtitle = "Anais 7º CBEm",
    y = "Termos",
    X = "Proporção"
  ) +
  theme(
    legend.position="bottom",
    legend.direction = "vertical"
  )
```


### Correlação de bigramas
```{r, fig.dim=c(8,8)}
merge(F, I, all = TRUE) %>%
  group_by(Pdf) %>%
  filter(
    any(Estado %in% Nordeste),
    Tipo == "Bigram"
  ) %>%
  group_by(Pdf, Termo) %>%
  filter(
    Autor == Autor[1]
  ) %>%
  select(-Autor) %>%
  count(Pdf, Modalidade, Eixo, Termo) %>%
  separate(Termo, c("Palavra1", "Palavra2"), sep = " ") %>%
  ungroup() %>%
  select(Palavra1, Palavra2, n) %>%
  filter(n > 7) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "kk") +
  geom_node_point(alpha=0, size = 5) +
  geom_edge_link(
    aes(color = "red"),
    show.legend = FALSE,
    arrow = grid::arrow(type = "closed", length = unit(.15, "inches"))
  ) +
  geom_node_text(aes(label = name)) +
  theme_void()
```

# Redes de colaborações
```{r, fig.dim=c(15, 15)}

edges = c()

add_edges = function(df) {
  df = df %>% distinct(Instituição)
  for (i in 1:nrow(df)) {
    for (j in 1:nrow(df)) {
      i1 = df$Instituição[i]
      i2 = df$Instituição[j]
      if (i < j && i1 != i2) {
        edges <<- c(edges, df$Instituição[i], df$Instituição[j])
      }
    }
  }
}

I %>%
  filter(Instituição != "") %>%
  select(Pdf, Instituição) %>%
  group_by(Pdf) %>%
  group_walk( ~ add_edges(.x))

g <- make_graph(edges, directed = FALSE)

g_simple = simplify(g)
E(g_simple)$weigth = sapply(E(g_simple), function(e) {
  length(all_shortest_paths(g, from=ends(g_simple, e)[1], to=ends(g_simple, e)[2])$res)
})

is_nordeste = left_join(
  as_tibble(list(Instituição=V(g)$name)),
  I %>%
    distinct(Instituição, .keep_all = TRUE)
) %>%
  select(Instituição, Estado) %>%
  transmute(
    IsNordeste = Estado %in% Nordeste
  ) %>%
  pull

plot(
  g_simple,
  layout = layout_with_kk,
  edge.width=E(g_simple)$weigth * 5,
  edge.label=E(g_simple)$weigth,
  edge.label.cex=2,
  vertex.color = factor(is_nordeste)
)
```
